# Generated by Django 2.0.1 on 2018-05-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.SmallIntegerField(default=0)),
                ('answer_text', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cid', models.UUIDField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('company_code', models.CharField(max_length=2, unique=True)),
                ('num_employees', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.UUIDField(primary_key=True, serialize=False)),
                ('secret_id', models.CharField(max_length=10)),
                ('has_answered', models.BooleanField(default=False)),
                ('answer_time', models.DateTimeField(blank=True, null=True)),
                ('e_type', models.CharField(blank=True, choices=[('', '- Level -'), ('UM', 'Upper Management'), ('MM', 'Middle Management'), ('LM', 'Lower Management'), ('OT', 'Other')], max_length=2)),
                ('job_area', models.CharField(blank=True, choices=[('', '- Department -'), ('E', 'Education'), ('HR', 'Human Resources'), ('F', 'Finance'), ('M', 'Management'), ('O', 'Other')], max_length=2)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagementSurvey.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('question_detail', models.CharField(blank=True, max_length=200)),
                ('has_info_box', models.BooleanField(default=True)),
                ('default_text', models.CharField(default='Add additional info', max_length=50)),
                ('question_type', models.CharField(choices=[('G', '1-7 Gallup'), ('GP', '1-7 Gallup with text box'), ('TB', 'Text box'), ('SO', 'Single option'), ('MO', 'Multiple option')], default='G', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='questions',
            field=models.ManyToManyField(blank=True, to='engagementSurvey.Question'),
        ),
        migrations.AddField(
            model_name='company',
            name='responses',
            field=models.ManyToManyField(blank=True, to='engagementSurvey.Answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagementSurvey.Employee'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagementSurvey.Question'),
        ),
    ]
