# Generated by Django 2.0.1 on 2018-05-15 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('engagementSurvey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
