# Generated by Django 2.0.1 on 2018-05-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagementSurvey', '0002_auto_20180515_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='_company_employees_+', to='engagementSurvey.Employee'),
        ),
    ]
