# Generated by Django 2.0.1 on 2018-05-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagementSurvey', '0004_auto_20180515_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cid',
            field=models.CharField(default='054ac05e-5854-11e8-a754-acbc32af581d', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(default='054b4134-5854-11e8-a8e8-acbc32af581d', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default='05482c4a-5854-11e8-88e0-acbc32af581d', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
