# Generated by Django 2.0.1 on 2018-05-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagementSurvey', '0005_auto_20180515_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='has_info_box',
        ),
        migrations.AlterField(
            model_name='company',
            name='cid',
            field=models.CharField(default='238ff89a-5854-11e8-b5e7-acbc32af581d', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(default='23907c66-5854-11e8-a35a-acbc32af581d', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default='238d799e-5854-11e8-82bf-acbc32af581d', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
