# Generated by Django 2.0.1 on 2018-05-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagementSurvey', '0006_auto_20180515_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['secret_id']},
        ),
        migrations.AlterField(
            model_name='company',
            name='cid',
            field=models.CharField(default='ff33371e-58e4-11e8-ac2a-acbc32af581d', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(default='ff33b57a-58e4-11e8-8ba9-acbc32af581d', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default='ff30cdc6-58e4-11e8-974d-acbc32af581d', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
